name: alarm_sms
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sms: ^0.2.0
  contacts_service: ^0.3.10
  permission_handler: ^4.1.0
  async: ^2.3.0
  timer_builder: ^1.3.0
  rflutter_alert: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
  assets:
    - assets/
